#include "lwip/ip_addr.h"
#include "lwip/pbuf.h"
#include <string.h>
#include <stdio.h>
#include <stdint.h>
#include "tusb.h"

#include <stdio.h>
#include <string.h>
#include "pico/stdlib.h"
#include "pico/cyw43_arch.h"
#include "lwip/udp.h"

#define WIFI_SSID "SSID"
#define WIFI_PASSWORD "PASSWORD"
#define DNS_PORT 53

extern "C" {
    // generated by emx-onnx-cgen
    void model(const float onnx__Gemm_0[1][4], float v_13[1]);
}

#define DNS_CLASSIFIER_FEATURES_COUNT 4

const float feature_mean[DNS_CLASSIFIER_FEATURES_COUNT] = { 102.406350f, 4.41414519f, 0.0983941086f, 0.200272403f };
const float feature_std[DNS_CLASSIFIER_FEATURES_COUNT]  = { 96.4387864f, 1.18921331f, 0.0837316504f, 0.220689143f };

#include <string>
#include <unordered_map>
#include <cmath>
#include <cctype>
#include <vector>

inline float digit_ratio(const std::string &s)
{
    if (s.empty())
        return 0.0;
    size_t count = 0;
    for (unsigned char ch : s) if (std::isdigit(ch)) ++count;
    return static_cast<float>(count) / s.size();
}

inline float shannon_entropy(const std::string &s)
{
    if (s.empty())
        return 0.0;
    std::unordered_map<unsigned char, size_t> freq;
    for (unsigned char ch : s) ++freq[ch];
    const float n = static_cast<float>(s.size());
    float ent = 0.0;
    for (const auto &p : freq)
    {
        float f = static_cast<float>(p.second) / n;
        ent -= f * std::log2(f);
    }
    return ent;
}

inline float length(const std::string &s)
{
    return s.size();
}

inline float uppercase_ratio(const std::string &s)
{
    if (s.empty())
        return 0.0;
    size_t count = 0;
    for (unsigned char ch : s) if (std::isupper(ch)) ++count;
    return static_cast<float>(count) / s.size();
}


void get_resolved_ip(const char* domain, uint8_t* ip_out) {
    printf("Got domain: %s\n", domain);

    //
    // get features
    //

    float raw_features[1][4] = {
        { length(domain), shannon_entropy(domain), digit_ratio(domain), uppercase_ratio(domain) }
    };
    float scaled_inputs[1][DNS_CLASSIFIER_FEATURES_COUNT];
    
    for (int i = 0; i < DNS_CLASSIFIER_FEATURES_COUNT; i++) {
        scaled_inputs[0][i] = (raw_features[0][i] - feature_mean[i]) / feature_std[i];
    }
    
    //printf("Digit ratio: %f, shannon_entropy: %f, length: %f, uppercase_ratio: %f\n", float_inputs[2], float_inputs[1], float_inputs[0], float_inputs[3]);

    float my_output[1] = { 0.0f };

    model(scaled_inputs, my_output);

    printf("--- ML Model Execution Complete ---\n");
    printf("Predicted Output Value: %f\n", my_output[0]);
    if (my_output[0] > 0.5f) {
        printf("⚠️ Malicious/Anomalous DNS Query Detected!\n");
    } else {
        printf("✅ Normal DNS Query.\n");
    }
}

// Low-latency UDP Receive Callback
void dns_recv_callback(void *arg, struct udp_pcb *pcb, struct pbuf *p, const ip_addr_t *addr, u16_t port) {
    printf("dns_recv_callback called\n");
    if (p != NULL) {
        uint8_t* data = (uint8_t*)p->payload;
        uint16_t len = p->tot_len;

        if (len >= 12) {
            char domain[256] = {0};
            int idx = 12;
            int dest_idx = 0;
            
            while (idx < len && data[idx] != 0 && dest_idx < 254) {
                int label_len = data[idx];
                idx++;
                for (int i = 0; i < label_len && idx < len; i++) {
                    domain[dest_idx++] = data[idx++];
                }
                domain[dest_idx++] = '.';
            }
            domain[dest_idx] = '\0';

            uint8_t ip_bytes[4];
            get_resolved_ip(domain, ip_bytes);

            int query_end = 12;
            while (query_end < len && data[query_end] != 0) {
                query_end++;
            }
            query_end += 5; // Null byte + Type(2) + Class(2)

            uint16_t resp_len = query_end + 16; // Question length + 16 bytes for A record answer
            struct pbuf *p_resp = pbuf_alloc(PBUF_TRANSPORT, resp_len, PBUF_RAM);

            if (p_resp != NULL) {
                uint8_t* resp_data = (uint8_t*)p_resp->payload;

                memcpy(resp_data, data, query_end);

                resp_data[2] = 0x81;
                resp_data[3] = 0x80;
                resp_data[6] = 0x00;
                resp_data[7] = 0x01;
                int offset = query_end;
                resp_data[offset++] = 0xc0; resp_data[offset++] = 0x0c; // Name pointer to offset 12
                resp_data[offset++] = 0x00; resp_data[offset++] = 0x01; // Type A
                resp_data[offset++] = 0x00; resp_data[offset++] = 0x02; // Class IN
                resp_data[offset++] = 0x00; resp_data[offset++] = 0x00; // TTL (60s)
                resp_data[offset++] = 0x00; resp_data[offset++] = 0x3c; 
                resp_data[offset++] = 0x00; resp_data[offset++] = 0x04; // Data Length (4 bytes)
                
                memcpy(&resp_data[offset], ip_bytes, 4);

                udp_sendto(pcb, p_resp, addr, port);
                pbuf_free(p_resp);
            }
        }
        pbuf_free(p);
    }
}

int main() {
    stdio_init_all();
    
    if (cyw43_arch_init()) {
        printf("Wi-Fi Init Failed\n");
        return -1;
    }

    cyw43_arch_enable_sta_mode();

    printf("Connecting to Wi-Fi...\n");
    if (cyw43_arch_wifi_connect_timeout_ms(WIFI_SSID, WIFI_PASSWORD, CYW43_AUTH_WPA2_AES_PSK, 30000)) {
        printf("Connect failed.\n");
        return -1;
    }
    printf("Connected! Pico IP: %s\n", ip4addr_ntoa(netif_ip4_addr(netif_default)));

    struct udp_pcb *pcb = udp_new();
    if (pcb != NULL) {
        err_t err = udp_bind(pcb, IP_ADDR_ANY, DNS_PORT);
        if (err == ERR_OK) {
            udp_recv(pcb, dns_recv_callback, NULL);
            printf("DNS Server listening on port %d...\n", DNS_PORT);
        } else {
            printf("Failed to bind UDP port.\n");
        }
    }

    cyw43_wifi_pm(&cyw43_state, cyw43_pm_value(CYW43_NO_POWERSAVE_MODE, 20, 1, 1, 1));
    while (true) {
        #if PICO_CYW43_ARCH_POLL
        cyw43_arch_poll();
        #endif
        sleep_ms(1);
    }
}