/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 41da8b8014d8d91730f9b136e09b1d442d921918a807a352c79238d083004886
 * Model name: model
 * Graph name: main_graph
 * Inputs: 1 Outputs: 1 Nodes: 6 Initializers: 7
 * IR version: 8
 * Model version: n/a
 * Domain: n/a
 * Producer: pytorch (version: 2.4.0)
 * Opset imports: ai.onnx=18
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>
#include <string.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

extern const float weight1_net_0_weight[16][4];
extern const float weight2_net_0_bias[16];
extern const float weight3_net_2_weight[8][16];
extern const float weight4_net_2_bias[8];
extern const float weight5_net_4_weight[1][8];
extern const float weight6_net_4_bias[1];
extern const int64_t weight7__constant_output_0[1];

/*
 * Weight 1:
 * Name: weight1_net_0_weight
 * Shape: (16, 4)
 * Elements: 64
 * Dtype: float
 */
const EMX_UNUSED float weight1_net_0_weight[16][4] = {
    {
        0x1.b7f8c2p-3f, -0x1.155acap-2f, 0x1.cd050ep-6f, 0x1.105f36p-1f
    },
    {
        0x1.38ca7ap-5f, -0x1.f511b6p-1f, 0x1.ec776cp-4f, -0x1.7582fep-3f
    },
    {
        0x1.7b1fd8p-1f, -0x1.046332p-1f, -0x1.343f7ap-3f, 0x1.7f9360p-3f
    },
    {
        0x1.e9ad7ap-7f, 0x1.b7640ap-1f, -0x1.24be12p-6f, -0x1.6db940p-3f
    },
    {
        0x1.2c35c8p-2f, 0x1.5f5202p-1f, 0x1.66b39ap-2f, -0x1.50cccap-2f
    },
    {
        0x1.04eac0p-2f, 0x1.1fcf1ep-2f, -0x1.1f3e92p-6f, -0x1.063d06p-1f
    },
    {
        -0x1.8675b0p-3f, 0x1.b91560p-3f, -0x1.592c60p-4f, -0x1.c26ac0p-4f
    },
    {
        -0x1.a682a0p-2f, 0x1.32b4eap+0f, -0x1.01077ep-2f, 0x1.1bed2ep-1f
    },
    {
        0x1.36ced8p-3f, 0x1.1f0cd8p-1f, -0x1.3f7af0p-1f, 0x1.cc05dep-1f
    },
    {
        0x1.61278ap-2f, 0x1.1be372p-1f, 0x1.168434p-1f, -0x1.7a893ep-5f
    },
    {
        -0x1.4bf612p-5f, 0x1.4daad0p-2f, -0x1.063bb4p-2f, -0x1.585952p-2f
    },
    {
        -0x1.bf7bbcp-1f, -0x1.b17ee2p-2f, -0x1.e60b94p-1f, -0x1.cdfacap-2f
    },
    {
        -0x1.3659b4p-3f, 0x1.0ce216p+0f, 0x1.742e62p-5f, -0x1.932724p-1f
    },
    {
        -0x1.7228e2p-1f, -0x1.07651cp+0f, -0x1.f5bff0p-2f, -0x1.85c6cap-2f
    },
    {
        -0x1.92144ap-2f, 0x1.ba49f8p-3f, 0x1.cf5cf0p-2f, -0x1.7d79e8p-3f
    },
    {
        -0x1.2b7a2ep-1f, -0x1.f86af8p-1f, -0x1.3e60ccp-2f, -0x1.616a7cp-1f
    }
};

/*
 * Weight 2:
 * Name: weight2_net_0_bias
 * Shape: (16,)
 * Elements: 16
 * Dtype: float
 */
const EMX_UNUSED float weight2_net_0_bias[16] = {
    0x1.31b93ap-5f, -0x1.1990bep-2f, 0x1.4b8f50p-4f, 0x1.156298p+0f, 0x1.5a9a38p-1f, -0x1.dc00eap-2f, -0x1.bdaa20p-2f, 0x1.356de0p-1f,
    0x1.6fa09cp-2f, 0x1.d03476p-2f, -0x1.03e468p-1f, -0x1.83ec7ap-4f, 0x1.b41a70p-2f, 0x1.50a494p-2f, 0x1.131760p-2f, -0x1.3ea654p-1f
};

/*
 * Weight 3:
 * Name: weight3_net_2_weight
 * Shape: (8, 16)
 * Elements: 128
 * Dtype: float
 */
const EMX_UNUSED float weight3_net_2_weight[8][16] = {
    {
        0x1.9c2576p-5f, 0x1.c46902p-4f, -0x1.e2092cp-3f, -0x1.039238p-3f, -0x1.f8fbaap-4f, 0x1.514b10p-3f, -0x1.1fce10p-3f, -0x1.ec2044p-3f,
        -0x1.54f6e6p-5f, -0x1.efbb5cp-3f, 0x1.887ec0p-5f, -0x1.3d5970p-3f, -0x1.28daacp-3f, -0x1.7e3492p-4f, 0x1.09aeeep-5f, -0x1.b39904p-3f
    },
    {
        -0x1.62088ep-2f, 0x1.6ccc1ep-1f, -0x1.8d78f6p-2f, -0x1.6f11cep+0f, -0x1.b876f6p-3f, 0x1.6156acp-3f, -0x1.acec80p-6f, -0x1.774e78p-1f,
        -0x1.80a1c6p-2f, 0x1.e35184p-3f, 0x1.1c2f9cp-5f, 0x1.155d9cp-1f, -0x1.77e398p-1f, 0x1.5ec7b4p-1f, -0x1.472638p-4f, 0x1.39cf8cp-1f
    },
    {
        0x1.d17ca8p-3f, -0x1.85f642p-1f, 0x1.18883cp-1f, 0x1.e2cd28p-1f, 0x1.40e85cp-2f, -0x1.763e72p-4f, 0x1.7362c0p-3f, 0x1.cbac56p-1f,
        0x1.575594p-1f, 0x1.9d301ep-4f, -0x1.dbe454p-11f, -0x1.51b816p-3f, 0x1.305032p-1f, 0x1.1f4bbcp-2f, 0x1.06bcaap-9f, -0x1.49d660p-3f
    },
    {
        0x1.375464p-3f, -0x1.8f7e9ep-1f, 0x1.3773a2p-2f, 0x1.a92e68p-1f, 0x1.9c3346p-2f, -0x1.9157c4p-3f, -0x1.6a1dd4p-3f, 0x1.002c0cp-1f,
        0x1.2d618cp-1f, 0x1.51add2p-2f, -0x1.9fb560p-7f, -0x1.9e07f0p-2f, 0x1.bd207ep-2f, 0x1.f22330p-2f, 0x1.89cd16p-3f, -0x1.081004p-2f
    },
    {
        -0x1.15691ep-1f, 0x1.dac49ap-1f, -0x1.fe32b8p-2f, -0x1.2b65b8p+0f, -0x1.b0ad24p-2f, -0x1.6d7d42p-3f, 0x1.93f6e0p-6f, -0x1.995952p-1f,
        -0x1.543f22p-1f, 0x1.73f85cp-3f, -0x1.491ceap-3f, 0x1.815044p-1f, -0x1.6143e0p-1f, 0x1.28cd3ap-1f, -0x1.303358p-5f, 0x1.086edep-1f
    },
    {
        -0x1.b3aba8p-3f, -0x1.68e65ap-4f, 0x1.437c40p-5f, -0x1.eced00p-4f, 0x1.62e8a0p-3f, -0x1.e4b318p-4f, 0x1.fe5a08p-3f, -0x1.25a340p-4f,
        -0x1.2985a8p-3f, -0x1.d66750p-3f, 0x1.a32a00p-3f, 0x1.ea6ee8p-4f, -0x1.a09ca8p-5f, 0x1.70e07ep-5f, 0x1.5e0752p-4f, -0x1.6268f0p-4f
    },
    {
        -0x1.12ffa8p-3f, 0x1.75ffd4p-3f, -0x1.0711f0p-4f, -0x1.9337c8p-4f, -0x1.a46310p-4f, 0x1.9ca53cp-3f, 0x1.711064p-3f, 0x1.606ab8p-4f,
        -0x1.e3f3f8p-3f, -0x1.493fd0p-5f, 0x1.fee69cp-3f, -0x1.da8028p-4f, -0x1.2881c8p-3f, -0x1.80fc40p-5f, -0x1.51a3f4p-3f, -0x1.903ec0p-6f
    },
    {
        -0x1.36a012p-1f, 0x1.03a0c6p+0f, -0x1.32dec4p-2f, -0x1.3bceeap+0f, -0x1.4d7cb0p-1f, 0x1.3654fap-3f, 0x1.815a40p-6f, -0x1.a00d30p-1f,
        -0x1.0acc66p-1f, -0x1.463196p-2f, 0x1.d0c9bep-3f, 0x1.1911bap-1f, -0x1.42a71ep-1f, 0x1.8adf6cp-1f, -0x1.32a2acp-2f, 0x1.b59aa8p-1f
    }
};

/*
 * Weight 4:
 * Name: weight4_net_2_bias
 * Shape: (8,)
 * Elements: 8
 * Dtype: float
 */
const EMX_UNUSED float weight4_net_2_bias[8] = {
    -0x1.460c5cp-9f, 0x1.c76448p-5f, 0x1.16965ep-1f, 0x1.12cf20p-1f, 0x1.0e40c8p-5f, -0x1.c289b8p-3f, -0x1.d3781cp-3f, 0x1.8b284ep-4f
};

/*
 * Weight 5:
 * Name: weight5_net_4_weight
 * Shape: (1, 8)
 * Elements: 8
 * Dtype: float
 */
const EMX_UNUSED float weight5_net_4_weight[1][8] = {
    {
        -0x1.348308p-2f, -0x1.a31114p-1f, 0x1.19539cp+0f, 0x1.f64bc0p-1f, -0x1.d9404ep-1f, 0x1.55a190p-4f, -0x1.51e8e0p-5f, -0x1.5b3a72p-1f
    }
};

/*
 * Weight 6:
 * Name: weight6_net_4_bias
 * Shape: (1,)
 * Elements: 1
 * Dtype: float
 */
const EMX_UNUSED float weight6_net_4_bias[1] = {
    0x1.4a58fep-1f
};

/*
 * Weight 7:
 * Name: weight7__constant_output_0
 * Shape: (1,)
 * Elements: 1
 * Dtype: int64
 */
const EMX_UNUSED int64_t weight7__constant_output_0[1] = {
    -1LL
};

static inline float ref_scalar_f32_relu(float a) {
    return a > 0.0f ? a : 0.0f;
}

/*
 * Node 0:
 * OpType: Gemm
 * Name: /net/net.0/Gemm
 * Inputs: onnx::Gemm_0, net.0.weight, net.0.bias
 * Outputs: /net/net.0/Gemm_output_0
 * Attrs:
 *   alpha: 1.0
 *   beta: 1.0
 *   transB: 1
 */
EMX_NODE_FN void node0__net_net_0_gemm(const float input_a[1][4], const float input_b[16][4], const float input_c[16], float output[1][16]) {
    for (idx_t i = 0; i < 1; ++i) {
        for (idx_t j = 0; j < 16; ++j) {
            float acc = 0.0f;
            for (idx_t k = 0; k < 4; ++k) {
                const float a_val = input_a[i][k];
                const float b_val = input_b[j][k];
                acc += a_val * b_val;
            }
            idx_t c_j = j;
            const float bias = input_c[c_j];
            output[i][j] = acc * 1.0f + bias * 1.0f;
        }
    }
}

/*
 * Node 1:
 * OpType: Relu
 * Name: /net/net.1/Relu
 * Inputs: /net/net.0/Gemm_output_0
 * Outputs: /net/net.1/Relu_output_0
 * Attrs: n/a
 */
EMX_NODE_FN void node1__net_net_1_relu(const float input0[1][16], float output[1][16]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        for (idx_t i1 = 0; i1 < 16; ++i1) {
            output[i0][i1] = ref_scalar_f32_relu(input0[i0][i1]);
        }
    }
}

/*
 * Node 2:
 * OpType: Gemm
 * Name: /net/net.2/Gemm
 * Inputs: /net/net.1/Relu_output_0, net.2.weight, net.2.bias
 * Outputs: /net/net.2/Gemm_output_0
 * Attrs:
 *   alpha: 1.0
 *   beta: 1.0
 *   transB: 1
 */
EMX_NODE_FN void node2__net_net_2_gemm(const float input_a[1][16], const float input_b[8][16], const float input_c[8], float output[1][8]) {
    for (idx_t i = 0; i < 1; ++i) {
        for (idx_t j = 0; j < 8; ++j) {
            float acc = 0.0f;
            for (idx_t k = 0; k < 16; ++k) {
                const float a_val = input_a[i][k];
                const float b_val = input_b[j][k];
                acc += a_val * b_val;
            }
            idx_t c_j = j;
            const float bias = input_c[c_j];
            output[i][j] = acc * 1.0f + bias * 1.0f;
        }
    }
}

/*
 * Node 3:
 * OpType: Relu
 * Name: /net/net.3/Relu
 * Inputs: /net/net.2/Gemm_output_0
 * Outputs: /net/net.3/Relu_output_0
 * Attrs: n/a
 */
EMX_NODE_FN void node3__net_net_3_relu(const float input0[1][8], float output[1][8]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        for (idx_t i1 = 0; i1 < 8; ++i1) {
            output[i0][i1] = ref_scalar_f32_relu(input0[i0][i1]);
        }
    }
}

/*
 * Node 4:
 * OpType: Gemm
 * Name: /net/net.4/Gemm
 * Inputs: /net/net.3/Relu_output_0, net.4.weight, net.4.bias
 * Outputs: /net/net.4/Gemm_output_0
 * Attrs:
 *   alpha: 1.0
 *   beta: 1.0
 *   transB: 1
 */
EMX_NODE_FN void node4__net_net_4_gemm(const float input_a[1][8], const float input_b[1][8], const float input_c[1], float output[1][1]) {
    for (idx_t i = 0; i < 1; ++i) {
        for (idx_t j = 0; j < 1; ++j) {
            float acc = 0.0f;
            for (idx_t k = 0; k < 8; ++k) {
                const float a_val = input_a[i][k];
                const float b_val = input_b[j][k];
                acc += a_val * b_val;
            }
            idx_t c_j = 0;
            const float bias = input_c[c_j];
            output[i][j] = acc * 1.0f + bias * 1.0f;
        }
    }
}

/*
 * Node 5:
 * OpType: Reshape
 * Name: /Reshape
 * Inputs: /net/net.4/Gemm_output_0, /Constant_output_0
 * Outputs: 13
 * Attrs:
 *   allowzero: 0
 */
EMX_NODE_FN void node5__reshape(const float input0[1][1], float output[1]) {
    const float *input0_data = (const float *)input0;
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        output[i0] = input0_data[i0];
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float onnx__Gemm_0[restrict 1][4], float v_13[restrict 1]) {
    float tmp0__net_net_0_Gemm_output_0[1][16];
    float tmp1__net_net_1_Relu_output_0[1][16];
    float tmp2__net_net_2_Gemm_output_0[1][8];
    float tmp3__net_net_3_Relu_output_0[1][8];
    float tmp4__net_net_4_Gemm_output_0[1][1];
    node0__net_net_0_gemm(onnx__Gemm_0, weight1_net_0_weight, weight2_net_0_bias, tmp0__net_net_0_Gemm_output_0);
    node1__net_net_1_relu(tmp0__net_net_0_Gemm_output_0, tmp1__net_net_1_Relu_output_0);
    node2__net_net_2_gemm(tmp1__net_net_1_Relu_output_0, weight3_net_2_weight, weight4_net_2_bias, tmp2__net_net_2_Gemm_output_0);
    node3__net_net_3_relu(tmp2__net_net_2_Gemm_output_0, tmp3__net_net_3_Relu_output_0);
    node4__net_net_4_gemm(tmp3__net_net_3_Relu_output_0, weight5_net_4_weight, weight6_net_4_bias, tmp4__net_net_4_Gemm_output_0);
    node5__reshape(tmp4__net_net_4_Gemm_output_0, v_13);
}
